# Generated by Django 3.2.7 on 2021-09-25 09:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_booking_guest_hotel_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departing_from', models.CharField(max_length=50)),
                ('arriving_to', models.CharField(max_length=50)),
                ('leave_date', models.DateTimeField(default=datetime.datetime(2021, 9, 25, 9, 59, 25, 171480))),
                ('return_date', models.DateTimeField(default=datetime.datetime(2021, 9, 25, 9, 59, 25, 171490))),
                ('returning', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.flight')),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField(default=datetime.datetime(2021, 9, 25, 9, 59, 25, 170509))),
                ('checkout_date', models.DateTimeField(default=datetime.datetime(2021, 9, 26, 9, 59, 25, 170532))),
                ('check_out', models.BooleanField(default=False)),
                ('no_of_guests', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=20)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.IntegerField(default=101)),
                ('seat_type', models.CharField(default='standard', max_length=200)),
                ('rate', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
                ('no_of_seats', models.IntegerField(default=3)),
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddField(
            model_name='seating',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.hotel'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.guest'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.hotel'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.room'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.passenger'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='seating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.seating'),
        ),
    ]
